// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inohrthysqwupzmwovzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlub2hydGh5c3F3dXB6bXdvdnpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODcxOTYsImV4cCI6MjA3MTI2MzE5Nn0.dvFV6-cUtY4r9zr_Wt8pGlbZtcb9YA3sbOGKodegeuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});